---
- hosts: all
  gather_facts: no
  become: yes
  become_method: sudo
  become_user: root
  vars:
    commands: 
      - "192.168.126.1   test01"
      - "192.168.126.2   test02"
      - "192.168.126.3   test03"
  tasks:
  - name: 配置hosts
    lineinfile: dest=/etc/hosts "{% for i in commands %} regexp={{ i }} line={{ i }} {% endfor %}"
    when: commands != ""