---
- hosts: all
  gather_facts: no
  become: yes
  become_method: sudo
  become_user: root
  vars:
    host_info: 
      - "192.168.126.1   test01"
      - "192.168.126.2   test02"
      - "192.168.126.3   test03"
    temp_file: "/etc/hosts"
  tasks:
  - name: template
    template: src=hosts.js dest={{ temp_file }}

  - name: 配置hosts
    shell: cat {{ temp_file }} >> /etc/hosts

  - name: 删除临时文件
    file: path={{ temp_file }} state=absent