---
- hosts: all
  gather_facts: no
  become: yes
  become_method: sudo
  become_user: root
  vars:
    contents: "192.168.126.1   test01\n192.168.126.2   test02\n192.168.126.3   test03"

  tasks:
  - name: 配置hosts
    blockinfile: path=/etc/hosts block={{ contents }} state=present
  # - name: 配置hosts
  #   {% for i in commands %} 
  #     dest=/etc/hosts  regexp={{ i }} line={{ i }} 
  #   {% endfor %}
  #   when: commands != ""