---
- hosts: all
  gather_facts: no
  become: yes
  become_method: sudo
  become_user: root
  vars:
    scripts_path: "/opt"
    bond_type: "0"
    miimon: "100"
    Ethernet1: ""
    Ethernet2: ""
    Ethernet3: ""
    Ethernet4: ""
    Ethernet5: ""
    Ethernet6: ""
#    cfg_file_path: "/etc/sysconfig/network-scripts/"
    ipaddress: ""
    PREFIX: ""
    GATEWAY: ""
    DNS1: ""
    DNS2: ""
    bonding_modules: "/etc/sysconfig/modules/bonding.modules"

  tasks:
  - name: 执行网卡绑定
    shell: chdir={{ scripts_path }} /bin/bash {{ scripts_path }}/bond.sh {{ bond_type }} {{ miimon }} {{ ipaddress }} {{ PREFIX }} {{ GATEWAY }} {{ DNS1 }} {{ DNS2 }} {{ Ethernet1 }} {{ Ethernet2 }} {{  Ethernet3 }} {{ Ethernet4 }} {{ Ethernet5 }} {{ Ethernet6 }}
    when:  bond_type != "" and ipaddress != "" and PREFIX != "" and GATEWAY != "" and DNS1 != ""
