---
- hosts: all
  gather_facts: no
  become: yes
  become_method: sudo
  become_user: root
  vars:
    scripts_path: "/opt"
    bond_type: ""
    miimon: "100"
    real1_name: ""
    real2_name: ""
    cfg_file_path: "/etc/sysconfig/network-scripts/"
    ipaddress: ""
    PREFIX: ""
    GATEWAY: ""
    DNS1: ""
    DNS2: ""
    bonding_modules: "/etc/sysconfig/modules/bonding.modules"

  tasks:
  - name: 执行网卡绑定
    shell: chdir={{ scripts_path }} /bin/bash {{ scripts_path }}/bond.sh {{ bond_type }} {{ miimon }} {{ real1_name }} {{ real2_name }} {{ ipaddress }} {{ PREFIX }} {{ GATEWAY }} {{ DNS1 }} {{ DNS2 }}
    when: real1_name != "" and real2_name != "" and bond_type != "" and ipaddress != "" and PREFIX != "" and GATEWAY != "" and DNS1 != ""
