---
- hosts: all
  gather_facts: no
  become: yes
  become_method: sudo
  become_user: root

  tasks:
  - name: 网络IO检测  
    shell: cat /proc/net/dev | awk '{ if($2!=0)  print $1" "$2" "$3" "$11" "$12}' | grep -vE "lo|Inter|face"
