---
- hosts: all
  gather_facts: no
  become: yes
  become_method: sudo
  become_user: root
  vars:
    serverid: "RedHat7.3"
    repo_name: "rhel7.3"
    baseurl: "ftp://132.96.178.39/pub/rhel7.3"
    enabled: "yes"
    gpgcheck: "yes"
    gpgkey: ""
    repo_file_name: "RedHat7"

    # #######       用户提供的仓库地址           #########
    # serverid: "repo for RedHat7.3"
    # repo_name: "rhel7.3"
    # baseurl: "http://132.122.137.3/RedHat/7/iso/RedHat7.3"
    # enabled: "yes"
    # gpgcheck: "yes"
    # gpgkey: ""
    # repo_file_name: "RedHat7"


  tasks:
    - name: 检测repo文件是否存在
      shell: ls /etc/yum.repos.d/{{ repo_file_name }}.repo | wc -l 
      register: file_count
      failed_when: file_count.stdout != "0"

    - name: 配置yum
      yum_repository:  file={{ repo_file_name }} name={{ serverid }} description={{ repo_name }} baseurl={{ baseurl }}  enabled={{ enabled }} gpgcheck={{ gpgcheck }} gpgkey={{ gpgkey }} state=present

    - name: 执行yum clean all
      shell: yum clean all
