---
- hosts: all
  gather_facts: no
  become: yes
  become_method: sudo
  become_user: root

  tasks:
  - name: 删除无关用户
    shell: userdel {{ item }}
    with_items:
       - "lp"
       - "sync"
       - "halt"
       - "news"
       - "uucp"
       - "operator"
       - "games"
       - "gopher"
       - "smmsp"
       - "nfsnobody"
       - "nobody"
    ignore_errors: yes
