---
- hosts: all
  gather_facts: no
  become: yes
  become_method: sudo
  become_user: root

  tasks:
  - name: 禁用 NetworkManager
    shell: systemctl disable NetworkManager

  - name: 停止 NetworkManager
    shell: systemctl stop NetworkManager
