---
- hosts: all
  gather_facts: no
  become: yes
  become_method: sudo
  become_user: root

  tasks:
  - name: 禁用 firewall
    shell: /sbin/chkconfig firewalld off

  - name: 停止 firewall
    #service: name=network state=stopped
    #async: 10
    shell: systemctl stop firewalld
