---
- hosts: all
  gather_facts: no
  become: yes
  become_method: sudo
  become_user: root

  tasks:
  - name: 获取top10目录
    shell: du -hsx /* | sort -rh | head -10

  - name: 获取top10文件
    shell: find / -printf '%s %p\n'| sort -nr | head -10
