---
- hosts: all
  gather_facts: no
  become: yes
  become_method: sudo
  become_user: root
  vars:
    username: ""

  tasks:
  - name: 获取用户{{ username }} crontab的内容
    shell: cat /var/spool/cron/{{ username }}
    when: username != ""
