---
- hosts: all
  gather_facts: no
  become: yes
  become_method: sudo
  become_user: root
  vars:
    username: "sdnmuser"
    password: "sendi@1234"
  
  tasks:
  - name: modify password for user {{ username }}
    shell: echo {{ username }}':'{{ password }} | chpasswd
