---
- hosts: all
  gather_facts: no
  become: yes
  become_method: sudo
  become_user: root
  vars:
    hostname: ""
  
  tasks:
  - name: modify hostname 
    #shell: hostnamectl set-hostname {{ hostname }}
    hostname: name={{ hostname }}
    when: hostname != ""
