---
- hosts: all
  gather_facts: no
  become: yes
  become_method: sudo
  become_user: root

  tasks:
  - name: 配置口令有效期
    lineinfile: dest=/etc/login.defs regexp='^SPASS_MAX_DAYS' line='PASS_MAX_DAYS   90'
  - lineinfile: dest=/etc/login.defs regexp='^PASS_MIN_DAYS' line='PASS_MAX_DAYS   10'
  - lineinfile: dest=/etc/login.defs regexp='^SPASS_WARN_AGE' line='PASS_MAX_DAYS   7'
